<!-- Please remove this file from your project -->
<template>
  <div
    class="flex flex-col justify-center min-h-screen bg-gray-100 sm:items-center sm:pt-0"
  >
    <div class="flex justify-center sm:pt-0">
      <ApicalLogo />
    </div>
    <h1 class="flex justify-center sm:pt-0 text-2xl font-bold">APICACAL</h1>
    <h2 class="flex justify-center mt-4 text-2xl bounce-in-top">
      Ça va chier des bûches !
    </h2>
  </div>
</template>

<script>
export default {
  name: 'NuxtTutorial',
}
</script>

<style lang="css" scoped>
.bounce-in-top {
  animation: bounce-in-top 1.5s 1s both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-7-9 18:17:27
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation bounce-in-top
 * ----------------------------------------
 */
@keyframes bounce-in-top {
  0% {
    transform: translateY(-500px);
    animation-timing-function: ease-in;
    opacity: 0;
  }
  38% {
    transform: translateY(0);
    animation-timing-function: ease-out;
    opacity: 1;
  }
  55% {
    transform: translateY(-65px);
    animation-timing-function: ease-in;
  }
  72% {
    transform: translateY(0);
    animation-timing-function: ease-out;
  }
  81% {
    transform: translateY(-28px);
    animation-timing-function: ease-in;
  }
  90% {
    transform: translateY(0);
    animation-timing-function: ease-out;
  }
  95% {
    transform: translateY(-8px);
    animation-timing-function: ease-in;
  }
  100% {
    transform: translateY(0);
    animation-timing-function: ease-out;
  }
}
</style>
